services:
  - type: web
    name: byteminds-sih-project
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 5001
      - key: LABELSURE_MODE
        value: production
      - key: VISION_PROVIDER
        value: tesseract
      - key: OCR_PROVIDER
        value: tesseract
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
